[package]
name = "image_to_mesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obj-exporter = "0.2"
image = "0.25.5"
imageproc = "0.25.0"
rgeometry = "0.10.0"
sdfer = "0.2.1"